name: Build and Push to DockerHub

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/login-service:latest .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/login-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/login-service:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/login-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/login-service:${{ env.IMAGE_TAG }}

